### ISSUE TITLE
Definir estructura de datos para una Actividad

### ISSUE THREAD

**Issue by albertotc99** [Xileon310/IV-Project#19]
Como **programador** necesito definir una estructura de datos que registre la información de una Actividad (Título y zona (objeto de la clase zona) según [M1](https://github.com/Xileon310/IV-Project/milestone/1)) en la que podrán participar los usuarios de la aplicación.  La actividad debe tener un **título** para que los usuarios sepan de que actividad se trata y para facilitar su búsqueda, y la **zona** es necesaria porque los usuarios necesitan saber dónde se realizará la actividad.

Necesario para HU01 #13

**Comment by Xileon310** [comment]
También habría que añadir un campo descripción para explicar la actividad

**Comment by Xileon310** [comment]
Deberíamos eliminar la lista de usuarios del objeto Actividad, pues no lo guardaremos en memoria del propio objeto.

**Comment by albertotc99** [comment]
@Xileon310, ¿será necesaria la descripción para la lógica de negocio?
Por otra parte en la descripción del problema que hay en el README pone que se pretende establecer una clasificación de las actividades en diferentes categorías, ¿sería necesario que la actividad tuviera un atributo que indicase la categoría?

**Comment by Xileon310** [comment]
Es un vestigio que quedó sin eliminar de la anterior implementación. En un principio no es necesaria, solo complementa.
Sí, clasificaremos las actividades en diferentes categorías., pero no debería ser imprescindible para la lógica de negocio, por lo que no la creo conveniente en el primer PMV.

**Comment by JJ** [comment]
¿De qué forma el código postal soluciona el problema de que los usuarios sepan dónde hacer la actividad?

**Comment by albertotc99** [comment]
Sí, es cierto.

**Comment by albertotc99** [comment]
En este caso se va a desarrollar un objeto-valor actividad, que es el objeto más básico relacionado con la lógica de negocio ya que representa las actividades que podrán realizar los usuarios de la aplicación. A partir de estas actividades, la participación de los usuarios en las mismas y su ubicación se realizarán informes, que son la lógica de negocio principal. 

La clase actividad, por tanto, debe contener:
* Algo que permita al usuario identificar qué actividad es en concreto. En este caso será el _título_ de la actividad
* El _lugar_ en el que se lleva a cabo
* Según hemos hablado, también será necesario incluir un _tipo_ que facilite las búsquedas de los usuarios y la generación de informes.

**Comment by Xileon310** [comment]
Sí, eso sería lo correcto
