### ISSUE TITLE
Entidad Usuario

### ISSUE THREAD

**Issue by albertotc99** [Xileon310/IV-Project#20]
La entidad Actividad tiene una lista de usuarios, por tanto para programar #19 es necesario tener previamente definida la entidad Usuario. 
Se ha considerado que el usuario es una entidad porque tiene identidad propia y es mutable. Contendrá los siguientes atributos:
* Nick
* Nombre
* Apellidos
* Zona (objeto Zona)

**Comment by albertotc99** [comment]
@Xileon310 , ¿Qué información debería tener esta clase?

**Comment by Xileon310** [comment]
Su nick (debería ser único), nombre, apellidos, zona en la que vive (objeto de tipo Zona), email y contraseña.

**Comment by Xileon310** [comment]
El usuario no alimenta la lógica de negocio, por lo que deberíamos eliminar esta clase.

**Comment by albertotc99** [comment]
👍🏼

**Comment by JJ** [comment]
Si no habéis cerrado con commit, os va a dar error.
