### ISSUE TITLE
Definir estructura de datos para una Zona

### ISSUE THREAD

**Issue by albertotc99** [Xileon310/IV-Project#21]
Como **programador**, para avanzar en #19, necesito diseñar una estructura de datos que represente las **_zonas_** en las que se desarrollarán las actividades con los atributos **localidad**, **provincia**, **pais** y **codigo postal**, siguiendo lo indicado en [M1](https://github.com/Xileon310/IV-Project/milestone/1). Es necesario definir las zonas con estos atributos para que quede registrado y los usuarios sepan el sitio concreto donde se realizará la actividad.

Necesario para avanzar en HU01 #13

**Comment by Xileon310** [comment]
Sí, es suficiente con esos atributos, caracterizan una zona perfectamente.

**Comment by albertotc99** [comment]
@Xileon310 , ¿hay alguno de los atributos que necesite un formato concreto? Y por otra parte, ¿es necesario el país para la lógica de negocio teniendo ya la localidad y codigo postal?

**Comment by Xileon310** [comment]
> ¿hay alguno de los atributos que necesite un formato concreto?

No, todos los atributos exceptuando el código postal serán strings. Bueno, realmente incluso el código postal podría ser una cadena de texto también, lo dejo a tu elección.

> ¿es necesario el país para la lógica de negocio teniendo ya la localidad y codigo postal?

Pensándolo detenidamente tienes razón, no es necesario el país, puesto que no puede existir dos zonas en diferentes países cuya localidad y código postal sea idéntico.

**Comment by albertotc99** [comment]
Investigando un poco sobre los [códigos postales](https://es.wikipedia.org/wiki/C%C3%B3digo_postal) he descubierto que hay países pequeños como Gibraltar o Hong Kong que no los utilizan, ya que no les hacen falta. Quizá sí sea necesario el país, aunque sea para algunos casos concretos y excepcionales.
Además hay algunos países como [Argentina](https://es.wikipedia.org/wiki/C%C3%B3digo_postal#En_Argentina) en los que se utilizan letras en el código postal, por tanto cambiaré su representación por string.

**Comment by Xileon310** [comment]
Me parece correcto entonces. Tiene sentido que países muy pequeños no usen CP. Respecto lo de las letras es la primera vez que lo leo.
