### ISSUE TITLE
Incluir categoria de la actividad

### ISSUE THREAD

**Issue by albertotc99** [Xileon310/IV-Project#23]
Para la lógica de negocio es necesario que la actividad incluya una categoría, como ocio, cultural, etc. De esta manera los informes que se generen podrán contener estadísticas sobre el tipo de actividad, y a los usuarios les resultará más sencillo encontrar la actividad que buscan.
Se tiene que aclarar cuantos tipos de actividad habría y cuáles serían.

**Comment by Xileon310** [comment]
En principio los tipos de actividades serían Ocio, Cultural, Deporte.
Creo que un tipo de dato enumerado estará bastante bien para ello.
